### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by Smilebags** [Smilebags/p5.dimensions.js#16]
The last thing to do before submitting this to be an addon to p5.js is to add some documentation explaining the concepts, maybe the structure of the nVector objects, and some basic use cases. I propose this should be done as a combination of the wiki of this repo and as files in the repo, maybe in a subdirectory. The current testing file could be the basis for this.

**Comment by Smilebags** [comment]
I have added an initial documentation page which should be sufficient to start with but a page with all functions and their use could be helpful as well.

**Comment by max0410** [comment]
Its seems that everything is done! Time to tell them to put it on the site!

**Comment by Smilebags** [comment]
I've emailed them with the links to this repo, when I hear back I'll let you know what's happening!

**Comment by max0410** [comment]
It looks like some of the libraries have banners, if we need one you could use this:
![download](https://cloud.githubusercontent.com/assets/16921177/22859727/b2be42dc-f0b4-11e6-9a3c-f3713054a3ea.jpg)

**Comment by Smilebags** [comment]
I like it! The title on the banners on their site is done in HTML so won't need to be added to the image, but the galaxy idea is great.  🌌
