### ISSUE TITLE
Resources for p5js.org website

### ISSUE THREAD

**Issue by Smilebags** [Smilebags/p5.dimensions.js#20]
We need a 400x118 greyscale image, one sentence description, and a by line.

I propose the image is a galaxy background with a hypercube on top or something along those lines.

The sentence could be:
p5.dimensions extends p5.js' vector functions to work in any number of dimensions.

And the by line to be:
Created by [Smilebags](https://github.com/Smilebags) and [Max Segal](https://github.com/max0410)

What do you think @max0410 ?

**Comment by Smilebags** [comment]
I've sent of an initial proposal but we can change it if needed.

**Comment by max0410** [comment]
I saw this on the website, so I guess its too late.

**Comment by Smilebags** [comment]
No, I think it is fine to get it changed any time.

**Comment by Smilebags** [comment]
I'll close this for now. If you would like to upgrade the image or change the description, just send the new version through to me or hello@p5js.org
