### ISSUE TITLE
Cross Product implementation

### ISSUE THREAD

**Issue by Smilebags** [Smilebags/p5.dimensions.js#5]
@max0410, as you can see in the code, nCross is empty. If you're familiar with this, it would be awesome to be able to add that too.

**Comment by max0410** [comment]
I just added a pull request. But keep in mind that cross functions only work with three dimensions

**Comment by Smilebags** [comment]
I had a suspicion that was true, and would explain why I couldn't figure out how to implement it in nD.. Thanks.
